/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "peripheral_config.h"
#include "stm32f7xx_timer_driver.h"
#include <stm32f756zg_reg.h>




uint8_t rx_byte;

GPIO_RegDef_t *led;
uint8_t button_state;
TIMER_handler_t timer2;
uint32_t count=0;
char buffer[20];
int len=0;
uint16_t i=0;

int main(void)
	{
	//uint8_t count=0;
	led_setup_red(&g_led3);
	button_setup(&g_button);
	timer2.TimerConfig.PreScaler=16000;
	timer2.TimerConfig.Period=1000;
	timer2.TimerConfig.direction=0;
//	uint8_t button_state;
	usart3_tx(&g_usart3_tx);
	usart3_rx(&g_usart3_rx);
	usart3_init(&g_usart3);
	TimerInit(&timer2);

	TimerControl(&timer2, ENABLE);
	USART_SendData(&g_usart3, (uint8_t*)"Getting Started\n\r", sizeof("Getting Started\n\r"));
	//timer2.pTimer->TIM_SR &= ~(1<<0);
	while(1)
	{
	    timer2.pTimer->TIM_SR &= ~(1<<0);
	    while(!(timer2.pTimer->TIM_SR & (1<<0))){
	    	count=TimerGetCount(&timer2);
	    }


	    GPIO_TogglePin(g_led3.pGPIOx, 14);
	}
	}




