/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "peripheral_config.h"


// Global handlers - persistent, accessible throughout main


int main(void){

    // Initialize all peripherals with their handlers
	board_init();
    
    uint8_t msg[] = "HELLO\r\n";
    
    while(1){
        //GPIO_TogglePin(g_led3.pGPIOx, 14);

    	USART_SendData(&g_usart3, msg, strlen(msg));
        for(volatile uint32_t i = 0; i < 200000; i++);  // crude delay
    }




}

